run:
  # Use CSV folder instead of single file
  input_dir: runs/sample_run_1/input  # This should be a folder containing CSV files
  output_processed_data: true
  use_input_prefix: false

# Groupby configuration - data will be grouped by these columns
# and Pareto selection will be run separately for each group
groupby_columns:
  - FP

visualization:
  dashboard_host: localhost
  dashboard_port: 8050
  generate_visualization: true

# Variable configuration for the new CSV format
data:
  # Single-value variables (direct column values)
  AREA:
    objective: minimize
    variable:
      type: single
    tolerance:
      type: relative
      value: 0.05
      
  OUT_CAP:
    objective: maximize
    variable:
      type: single
    tolerance:
      type: absolute
      value: 1.0
      
  LEAKAGE:
    objective: minimize
    variable:
      type: single
    tolerance:
      type: relative
      value: 0.1

  # Multi-value variables with simplified selection
  DYNAMIC:
    objective: minimize
    variable:
      type: multi
      selection_strategy: index
      idx1_value: 1
      idx2_value: 2
    tolerance:
      type: relative
      value: 0.15

  TRANSITION:
    objective: minimize
    variable:
      type: multi
      selection_strategy: value
      idx1_value: 0.12
      idx2_value: 1.2
    tolerance:
      type: absolute
      value: 0.5

  DELAY:
    objective: minimize
    variable:
      type: multi
      selection_strategy: value
      idx1_value: 25
      idx2_value: 250
    tolerance:
      type: relative
      value: 0.1