data:
  AREA:
    objective: minimize
    tolerance:
      type: relative
      value: 0.05
    variable:
      type: single
  DELAY:
    objective: minimize
    tolerance:
      type: relative
      value: 0.1
    variable:
      idx1_values:
      - 10
      - 20
      - 30
      - 40
      - 50
      idx2_values:
      - 100
      - 200
      - 300
      - 400
      - 500
      selected_idx1: 25
      selected_idx2: 250
      selection_strategy: idx_based
      type: multi
  DYNAMIC:
    objective: minimize
    tolerance:
      type: relative
      value: 0.15
    variable:
      idx1_values:
      - 0.1
      - 0.2
      - 0.3
      - 0.4
      - 0.5
      idx2_values:
      - 1.0
      - 2.0
      - 3.0
      - 4.0
      - 5.0
      selected_idx1: 0.25
      selected_idx2: 2.5
      selection_strategy: idx_based
      type: multi
  LEAKAGE:
    objective: minimize
    tolerance:
      type: relative
      value: 0.1
    variable:
      type: single
  OUT_CAP:
    objective: maximize
    tolerance:
      type: absolute
      value: 1.0
    variable:
      type: single
  TRANSITION:
    objective: minimize
    tolerance:
      type: absolute
      value: 0.5
    variable:
      idx1_values:
      - 0.05
      - 0.1
      - 0.15
      - 0.2
      - 0.25
      idx2_values:
      - 0.5
      - 1.0
      - 1.5
      - 2.0
      - 2.5
      selected_idx1: 0.12
      selected_idx2: 1.2
      selection_strategy: idx_based
      type: multi
groupby_columns:
- FP
- STD
run:
  input_file: sample_data.csv
  output_processed_data: true
  use_input_prefix: true
visualization:
  dashboard_host: localhost
  dashboard_port: 8050
  generate_visualization: false
